version: '{build}'
build_script:
- npm -g install npm@2
- set PATH=%APPDATA%\npm;%PATH%
- npm install -g gulp
- npm install
- gulp --mode Release
test: off
# artifacts:
# - path: build\deploy\*.nupkg
#   name: NugetPackages
